// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTPMW-KWpXuvhLqtAfdGen4Fml9i3Qy2o',
    appId: '1:328692582403:web:3bb988992ab77906046636',
    messagingSenderId: '328692582403',
    projectId: 'word-search-25',
    authDomain: 'word-search-25.firebaseapp.com',
    storageBucket: 'word-search-25.firebasestorage.app',
    measurementId: 'G-FMVWKRBG3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_UV9Br1xk46U4d1xWLvwDfJ4EBgE7xRg',
    appId: '1:328692582403:android:9d775ecff45eb8c5046636',
    messagingSenderId: '328692582403',
    projectId: 'word-search-25',
    storageBucket: 'word-search-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0M83aDVRCXjAo1HWjTcqkUYFpc22w4e8',
    appId: '1:328692582403:ios:b86a5ea89e11d645046636',
    messagingSenderId: '328692582403',
    projectId: 'word-search-25',
    storageBucket: 'word-search-25.firebasestorage.app',
    iosBundleId: 'com.subnext.wordsearch',
  );
}
